### ISSUE TITLE
Wolf_explorer tuto... 

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_navigation#7]
Hello the team.
When launching exploration, it starts with spot and Lidar,
When I call stand-up service, spot jumps and falls.

Any tuto, for a correct exploration?

**Comment by graiola** [comment]
did you install the dependencies?

**Comment by elpimous** [comment]
made a git pull, and reinstalled all requirements. Now, stand up correctly !!! Good.
How to let robot walk and build map in this explorer launch ?

**Comment by graiola** [comment]
the robot should explore automatically the environment. You can use the `world_name:=office`and see how it goes. Also, if you have version `0.0.9` and the last commit of `wolf_navigation` you can use the keyboard/joypad as well to take back control while the robot explores.

**Comment by elpimous** [comment]
Hello, graiola,
when launching : roslaunch wolf_navigation wolf_exploration.launch world_name:=office
i have rviz errors, with a white partial robot on floor, see pict.
https://ibb.co/R41STYL
I have both last soft versions

**Comment by elpimous** [comment]
hello, after a reboot, i can see colored robot, after nearly 5-7s.
But, just after a "enter" keyboard press, robot starts to stand up, then dances anything like hip hop, then shuts down...
Anything like if walk params weren't setup ?!!!

**Comment by graiola** [comment]
Are you sure that you are using our `spot_description`?

**Comment by elpimous** [comment]
well, i had success... Bad wolf_gazebo_models sourcing !!
Working very well, thanks.
